Premiumizer.py
README.md
myjdapi.py
requirements.txt
settings.cfg.tpl
templates/settings.html

Need to test: new requirement Pycrypto might not install without a compiler ?

This fixes error when auto remove cloud is enabled, + copylinks replace for my jdownloader support

---

Premiumizer.py

first scheduler & socketio can 'gracefully ? xD' shutdown & then force everything to stop :)

Fix force all threads to exit, first shut shed & socketio

---

Premiumizer.py

Rename JD variables

---

Premiumizer.py

Fix hanging loading download

---

Premiumizer.py

This fixes program hang when premiumize.me does not respond

Requests: use session, timeout & retry

---

Premiumizer.py
static/js/control.js
templates/index.html

Got email back from premiumize.me dev, api to be used changed to https://www.premiumize.me/api
added support for nzb's

Premiumizer API update / add nzb support

---

premiumizer.py

utf-8 log & history: fix UnicodeDecodeError

---

premiumizer.py
requirements.txt
settings.cfg.tpl

Do not always clear (delete & reopen database file), only if it existed & has keys
bump req

Do not always clear (delete & reopen database file), only if it existed & has keys

---

premiumizer.py

Updates & bug fixes

---

premiumizer.py

downloads where not working after previous commit

major bug fix

---

premiumizer.py
settings.cfg.tpl
templates/settings.html

add download everything switch in settings

---

premiumizer.py

fix some bugs on empty config file

---

Dockerfile

Added tzdata to docker image. This enables the TZ env var.

---

static/css/style.css
templates/base.html

Previous PR messed up mobile view with css change..

fix mobile view

---

premiumizer.py
requirements.txt
settings.cfg.tpl

Fix stuck tasks because wrong folder_id I guess premiumize.me changed the folder_Id when a download is finished in the cloud as to when it started recently because I had a lot of stuck downloads.

Fix stuck tasks

---

premiumizer.py

well I added this again since clean_name didn't do what I thought it would.
probably isn't right but it works.

urllib.decode add_task first

---

premiumizer/utils.py

Update from ui was broken because of previous changes
- logs folder inside conf folder
- settings.cfg.tpl inside premiumizer folder

fix utils.py

---

premiumizer/premiumizer.py

fix referenced before assignment in rare case..

---

premiumizer/premiumizer.py
premiumizer/settings.cfg.tpl
premiumizer/templates/settings.html
requirements.txt

Add own support for reverse proxy / URL base

---

README.md

they are still a little vague, but should help those who just copy and pasted what you originally had :)

update mac instructions

---

premiumizer/templates/base.html

Used slim build but it doesn't have Ajax and broke home page =(

Fix jquery

---

premiumizer/premiumizer.py

Update task name from premiumize.me

---

premiumizer/premiumizer.py
premiumizer/static/js/control.js
premiumizer/templates/index.html

once the list gets a bit fuller, it's really annoying to clean up the failed downloads one by one.

add a button to delete all tasks with the cloud status 'error'

---

premiumizer/premiumizer.py
premiumizer/settings.cfg.tpl
premiumizer/templates/settings.html

Closes #205 
I had to move `MyHandler` class up to make it available as global variable, because both `watchdir` and `walk_watchdir` access the watchdog handler now. I am not sure if this is the right way to implement this. If you have other ideas that fit your code style better, please feel free to make changes or contact me.
Config file needs to be changed for this to work, otherwise it misses the two new options `watchdir_walk_enabled` and `watchdir_walk_interval`.

Add blackhole scan by interval

---

premiumizer/premiumizer.py
premiumizer/settings.cfg.tpl
premiumizer/templates/settings.html

custom domain option to make new socketio work
some more work on settings.html

and more bugfixes

---

premiumizer/premiumizer.py

#223 should finally work now =D
some more code in there was working on #228

bugfix again

---

premiumizer/static/css/style.css
premiumizer/static/js/control.js
premiumizer/templates/history.html

fixing the layout of home, history and log.
magnet links can be extremly long and glitch out the gui.

gui improvements

---

premiumizer/premiumizer.py
premiumizer/settings.cfg.tpl
premiumizer/static/js/control.js
premiumizer/templates/history.html
premiumizer/templates/index.html
premiumizer/templates/log.html

reduced task name from 120 to 100 as no monospace font is used and 120 wasnt enough, fixed a exception in history.html returning 500 due to malformed log ? task.info was not set and threw an error, reduced updater interval from 10 to 3 seconds to make it more responsive.

improvements / fixes

---

Dockerfile

-Added tzdata apk, copy zoneinfo into image, TZ EV doesn't have any affect without it.  
-Updated 'python-dev' apk to 'python3-dev', original name isn't available, breaks build

Fix TZ data for logs

---

Dockerfile
Dockerfile.arm32v7
Dockerfile.arm64v8

Fixes #276. I just added libstdc++, now the container starts up like it's supposed to again.

Fixed libstdc++ error

---

premiumizer/premiumizer.py
premiumizer/settings.cfg.tpl
premiumizer/templates/settings.html
requirements.txt

Integrates [Apprise](https://github.com/caronc/apprise) for push notifications. Adds a new "Apprise" section to the notifications settings:
Tested with Telegram:
I don't actually know Python so let me know if anything looks weird 😅
Closes #287

Integrate Apprise for push notifications
